name: andinatech_flutter_assessment
description: "Technical assessment for flutter job position"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  http: ^1.2.1

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/beneficiaries.json

  uses-material-design: true
